-- Segment 3: structured Bulk exercise library. Existing workouts continue to use
-- their stored exercise names; this catalog is additive and does not rewrite history.
CREATE TABLE public.bulk_exercises (
  id text PRIMARY KEY DEFAULT ('custom:' || gen_random_uuid()::text),
  owner_id uuid DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  slug text NOT NULL,
  name text NOT NULL,
  primary_muscle text NOT NULL,
  secondary_muscles text[] NOT NULL DEFAULT '{}',
  equipment text[] NOT NULL,
  movement_pattern text NOT NULL,
  category text NOT NULL DEFAULT 'strength',
  supports_unilateral boolean NOT NULL DEFAULT false,
  default_unilateral_mode text NOT NULL DEFAULT 'bilateral',
  is_bodyweight boolean NOT NULL DEFAULT false,
  is_system boolean NOT NULL DEFAULT false,
  active boolean NOT NULL DEFAULT true,
  min_experience text NOT NULL DEFAULT 'beginner',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT bulk_exercises_name_ck CHECK (char_length(btrim(name)) BETWEEN 2 AND 80),
  CONSTRAINT bulk_exercises_slug_ck CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  CONSTRAINT bulk_exercises_primary_muscle_ck CHECK (primary_muscle = ANY (ARRAY['chest','lats','upper_back','traps','front_delts','side_delts','rear_delts','biceps','triceps','forearms','quads','hamstrings','glutes','calves','adductors','abductors','abs','obliques','lower_back'])),
  CONSTRAINT bulk_exercises_secondary_muscles_ck CHECK (secondary_muscles <@ ARRAY['chest','lats','upper_back','traps','front_delts','side_delts','rear_delts','biceps','triceps','forearms','quads','hamstrings','glutes','calves','adductors','abductors','abs','obliques','lower_back']::text[] AND NOT primary_muscle = ANY (secondary_muscles)),
  CONSTRAINT bulk_exercises_equipment_ck CHECK (cardinality(equipment) > 0 AND equipment <@ ARRAY['barbell','dumbbell','cable','machine','smith_machine','bench','pull_up_bar','bodyweight','kettlebell','resistance_band','plate','trap_bar','ez_bar']::text[]),
  CONSTRAINT bulk_exercises_movement_pattern_ck CHECK (movement_pattern = ANY (ARRAY['horizontal_push','vertical_push','horizontal_pull','vertical_pull','squat','hinge','lunge','knee_extension','knee_flexion','hip_extension','hip_abduction','hip_adduction','elbow_flexion','elbow_extension','shoulder_abduction','shoulder_flexion','shoulder_extension','calf_raise','core_flexion','anti_extension','anti_rotation','rotation','carry','other'])),
  CONSTRAINT bulk_exercises_category_ck CHECK (category IN ('strength','bodyweight','core','carry')),
  CONSTRAINT bulk_exercises_unilateral_ck CHECK (default_unilateral_mode IN ('bilateral','unilateral') AND (supports_unilateral OR default_unilateral_mode = 'bilateral')),
  CONSTRAINT bulk_exercises_experience_ck CHECK (min_experience IN ('beginner','intermediate','advanced')),
  CONSTRAINT bulk_exercises_origin_ck CHECK ((is_system AND owner_id IS NULL AND id LIKE 'system:%') OR (NOT is_system AND owner_id IS NOT NULL AND id LIKE 'custom:%'))
);

CREATE UNIQUE INDEX bulk_exercises_system_slug_uidx ON public.bulk_exercises(slug) WHERE is_system;
CREATE UNIQUE INDEX bulk_exercises_owner_slug_uidx ON public.bulk_exercises(owner_id, slug) WHERE NOT is_system;
CREATE INDEX bulk_exercises_name_idx ON public.bulk_exercises(lower(name));
CREATE INDEX bulk_exercises_primary_muscle_idx ON public.bulk_exercises(primary_muscle);
CREATE INDEX bulk_exercises_equipment_idx ON public.bulk_exercises USING gin(equipment);
CREATE INDEX bulk_exercises_owner_idx ON public.bulk_exercises(owner_id) WHERE owner_id IS NOT NULL;
CREATE TRIGGER bulk_exercises_touch BEFORE UPDATE ON public.bulk_exercises
FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

CREATE FUNCTION private.has_active_bulk()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $function$
  SELECT (SELECT auth.uid()) IS NOT NULL AND EXISTS (
    SELECT 1 FROM public.bulk_members
    WHERE user_id = (SELECT auth.uid()) AND role = 'owner'
  )
$function$;

REVOKE ALL ON FUNCTION private.has_active_bulk() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION private.has_active_bulk() TO authenticated, service_role;

ALTER TABLE public.bulk_exercises ENABLE ROW LEVEL SECURITY;
CREATE POLICY "bulk exercises read library" ON public.bulk_exercises
FOR SELECT TO authenticated
USING (private.has_active_bulk() AND (is_system OR owner_id = (SELECT auth.uid())));
CREATE POLICY "bulk exercises create own custom" ON public.bulk_exercises
FOR INSERT TO authenticated
WITH CHECK (private.has_active_bulk() AND NOT is_system AND owner_id = (SELECT auth.uid()));
CREATE POLICY "bulk exercises update own custom" ON public.bulk_exercises
FOR UPDATE TO authenticated
USING (private.has_active_bulk() AND NOT is_system AND owner_id = (SELECT auth.uid()))
WITH CHECK (private.has_active_bulk() AND NOT is_system AND owner_id = (SELECT auth.uid()));
CREATE POLICY "bulk exercises delete own custom" ON public.bulk_exercises
FOR DELETE TO authenticated
USING (private.has_active_bulk() AND NOT is_system AND owner_id = (SELECT auth.uid()));

GRANT SELECT, INSERT, UPDATE, DELETE ON public.bulk_exercises TO authenticated;
GRANT ALL ON public.bulk_exercises TO service_role;

CREATE TEMP TABLE bulk_exercise_seed (
  slug text, name text, primary_muscle text, secondary_muscles text[], equipment text[],
  movement_pattern text, category text, supports_unilateral boolean,
  default_unilateral_mode text, is_bodyweight boolean, min_experience text
);
INSERT INTO bulk_exercise_seed VALUES
  ('flat-barbell-bench-press', 'Flat Barbell Bench Press', 'chest', ARRAY['triceps','front_delts']::text[], ARRAY['barbell','bench']::text[], 'horizontal_push', 'strength', false, 'bilateral', false, 'beginner'),
  ('incline-barbell-bench-press', 'Incline Barbell Bench Press', 'chest', ARRAY['triceps','front_delts']::text[], ARRAY['barbell','bench']::text[], 'horizontal_push', 'strength', false, 'bilateral', false, 'beginner'),
  ('decline-barbell-bench-press', 'Decline Barbell Bench Press', 'chest', ARRAY['triceps','front_delts']::text[], ARRAY['barbell','bench']::text[], 'horizontal_push', 'strength', false, 'bilateral', false, 'beginner'),
  ('close-grip-barbell-bench-press', 'Close-Grip Barbell Bench Press', 'chest', ARRAY['triceps','front_delts']::text[], ARRAY['barbell','bench']::text[], 'horizontal_push', 'strength', false, 'bilateral', false, 'beginner'),
  ('wide-grip-barbell-bench-press', 'Wide-Grip Barbell Bench Press', 'chest', ARRAY['triceps','front_delts']::text[], ARRAY['barbell','bench']::text[], 'horizontal_push', 'strength', false, 'bilateral', false, 'beginner'),
  ('paused-barbell-bench-press', 'Paused Barbell Bench Press', 'chest', ARRAY['triceps','front_delts']::text[], ARRAY['barbell','bench']::text[], 'horizontal_push', 'strength', false, 'bilateral', false, 'beginner'),
  ('floor-barbell-press', 'Floor Barbell Press', 'chest', ARRAY['triceps','front_delts']::text[], ARRAY['barbell','bench']::text[], 'horizontal_push', 'strength', false, 'bilateral', false, 'beginner'),
  ('spoto-press', 'Spoto Press', 'chest', ARRAY['triceps','front_delts']::text[], ARRAY['barbell','bench']::text[], 'horizontal_push', 'strength', false, 'bilateral', false, 'beginner'),
  ('flat-dumbbell-bench-press', 'Flat Dumbbell Bench Press', 'chest', ARRAY['triceps','front_delts']::text[], ARRAY['dumbbell','bench']::text[], 'horizontal_push', 'strength', true, 'bilateral', false, 'beginner'),
  ('incline-dumbbell-bench-press', 'Incline Dumbbell Bench Press', 'chest', ARRAY['triceps','front_delts']::text[], ARRAY['dumbbell','bench']::text[], 'horizontal_push', 'strength', true, 'bilateral', false, 'beginner'),
  ('decline-dumbbell-bench-press', 'Decline Dumbbell Bench Press', 'chest', ARRAY['triceps','front_delts']::text[], ARRAY['dumbbell','bench']::text[], 'horizontal_push', 'strength', true, 'bilateral', false, 'beginner'),
  ('neutral-grip-dumbbell-press', 'Neutral-Grip Dumbbell Press', 'chest', ARRAY['triceps','front_delts']::text[], ARRAY['dumbbell','bench']::text[], 'horizontal_push', 'strength', true, 'bilateral', false, 'beginner'),
  ('dumbbell-floor-press', 'Dumbbell Floor Press', 'chest', ARRAY['triceps','front_delts']::text[], ARRAY['dumbbell','bench']::text[], 'horizontal_push', 'strength', true, 'bilateral', false, 'beginner'),
  ('dumbbell-squeeze-press', 'Dumbbell Squeeze Press', 'chest', ARRAY['triceps','front_delts']::text[], ARRAY['dumbbell','bench']::text[], 'horizontal_push', 'strength', true, 'bilateral', false, 'beginner'),
  ('alternating-dumbbell-bench-press', 'Alternating Dumbbell Bench Press', 'chest', ARRAY['triceps','front_delts']::text[], ARRAY['dumbbell','bench']::text[], 'horizontal_push', 'strength', true, 'bilateral', false, 'beginner'),
  ('flat-smith-machine-bench-press', 'Flat Smith Machine Bench Press', 'chest', ARRAY['triceps','front_delts']::text[], ARRAY['smith_machine','bench']::text[], 'horizontal_push', 'strength', false, 'bilateral', false, 'beginner'),
  ('incline-smith-machine-bench-press', 'Incline Smith Machine Bench Press', 'chest', ARRAY['triceps','front_delts']::text[], ARRAY['smith_machine','bench']::text[], 'horizontal_push', 'strength', false, 'bilateral', false, 'beginner'),
  ('decline-smith-machine-bench-press', 'Decline Smith Machine Bench Press', 'chest', ARRAY['triceps','front_delts']::text[], ARRAY['smith_machine','bench']::text[], 'horizontal_push', 'strength', false, 'bilateral', false, 'beginner'),
  ('smith-machine-guillotine-press', 'Smith Machine Guillotine Press', 'chest', ARRAY['triceps','front_delts']::text[], ARRAY['smith_machine','bench']::text[], 'horizontal_push', 'strength', false, 'bilateral', false, 'beginner'),
  ('machine-chest-press', 'Machine Chest Press', 'chest', ARRAY['triceps','front_delts']::text[], ARRAY['machine']::text[], 'horizontal_push', 'strength', true, 'bilateral', false, 'beginner'),
  ('incline-machine-chest-press', 'Incline Machine Chest Press', 'chest', ARRAY['triceps','front_delts']::text[], ARRAY['machine']::text[], 'horizontal_push', 'strength', true, 'bilateral', false, 'beginner'),
  ('decline-machine-chest-press', 'Decline Machine Chest Press', 'chest', ARRAY['triceps','front_delts']::text[], ARRAY['machine']::text[], 'horizontal_push', 'strength', true, 'bilateral', false, 'beginner'),
  ('converging-chest-press', 'Converging Chest Press', 'chest', ARRAY['triceps','front_delts']::text[], ARRAY['machine']::text[], 'horizontal_push', 'strength', true, 'bilateral', false, 'beginner'),
  ('plate-loaded-chest-press', 'Plate-Loaded Chest Press', 'chest', ARRAY['triceps','front_delts']::text[], ARRAY['machine']::text[], 'horizontal_push', 'strength', true, 'bilateral', false, 'beginner'),
  ('single-arm-machine-chest-press', 'Single-Arm Machine Chest Press', 'chest', ARRAY['triceps','front_delts']::text[], ARRAY['machine']::text[], 'horizontal_push', 'strength', true, 'bilateral', false, 'beginner'),
  ('standing-cable-chest-press', 'Standing Cable Chest Press', 'chest', ARRAY['front_delts']::text[], ARRAY['cable']::text[], 'horizontal_push', 'strength', true, 'bilateral', false, 'beginner'),
  ('seated-cable-chest-press', 'Seated Cable Chest Press', 'chest', ARRAY['front_delts']::text[], ARRAY['cable']::text[], 'horizontal_push', 'strength', true, 'bilateral', false, 'beginner'),
  ('single-arm-cable-chest-press', 'Single-Arm Cable Chest Press', 'chest', ARRAY['front_delts']::text[], ARRAY['cable']::text[], 'horizontal_push', 'strength', true, 'bilateral', false, 'beginner'),
  ('cable-crossover', 'Cable Crossover', 'chest', ARRAY['front_delts']::text[], ARRAY['cable']::text[], 'horizontal_push', 'strength', true, 'bilateral', false, 'beginner'),
  ('mid-cable-fly', 'Mid Cable Fly', 'chest', ARRAY['front_delts']::text[], ARRAY['cable']::text[], 'horizontal_push', 'strength', true, 'bilateral', false, 'beginner'),
  ('low-to-high-cable-fly', 'Low-to-High Cable Fly', 'chest', ARRAY['front_delts']::text[], ARRAY['cable']::text[], 'horizontal_push', 'strength', true, 'bilateral', false, 'beginner'),
  ('high-to-low-cable-fly', 'High-to-Low Cable Fly', 'chest', ARRAY['front_delts']::text[], ARRAY['cable']::text[], 'horizontal_push', 'strength', true, 'bilateral', false, 'beginner'),
  ('lying-cable-fly', 'Lying Cable Fly', 'chest', ARRAY['front_delts']::text[], ARRAY['cable']::text[], 'horizontal_push', 'strength', true, 'bilateral', false, 'beginner'),
  ('single-arm-cable-fly', 'Single-Arm Cable Fly', 'chest', ARRAY['front_delts']::text[], ARRAY['cable']::text[], 'horizontal_push', 'strength', true, 'bilateral', false, 'beginner'),
  ('pec-deck-fly', 'Pec Deck Fly', 'chest', ARRAY['front_delts']::text[], ARRAY['machine']::text[], 'horizontal_push', 'strength', false, 'bilateral', false, 'beginner'),
  ('machine-fly', 'Machine Fly', 'chest', ARRAY['front_delts']::text[], ARRAY['machine']::text[], 'horizontal_push', 'strength', false, 'bilateral', false, 'beginner'),
  ('push-up', 'Push-Up', 'chest', ARRAY['triceps','front_delts']::text[], ARRAY['bodyweight']::text[], 'horizontal_push', 'bodyweight', true, 'bilateral', true, 'beginner'),
  ('wide-push-up', 'Wide Push-Up', 'chest', ARRAY['triceps','front_delts']::text[], ARRAY['bodyweight']::text[], 'horizontal_push', 'bodyweight', true, 'bilateral', true, 'beginner'),
  ('narrow-push-up', 'Narrow Push-Up', 'chest', ARRAY['triceps','front_delts']::text[], ARRAY['bodyweight']::text[], 'horizontal_push', 'bodyweight', true, 'bilateral', true, 'beginner'),
  ('decline-push-up', 'Decline Push-Up', 'chest', ARRAY['triceps','front_delts']::text[], ARRAY['bodyweight']::text[], 'horizontal_push', 'bodyweight', true, 'bilateral', true, 'beginner'),
  ('incline-push-up', 'Incline Push-Up', 'chest', ARRAY['triceps','front_delts']::text[], ARRAY['bodyweight']::text[], 'horizontal_push', 'bodyweight', true, 'bilateral', true, 'beginner'),
  ('deficit-push-up', 'Deficit Push-Up', 'chest', ARRAY['triceps','front_delts']::text[], ARRAY['bodyweight']::text[], 'horizontal_push', 'bodyweight', true, 'bilateral', true, 'beginner'),
  ('paused-push-up', 'Paused Push-Up', 'chest', ARRAY['triceps','front_delts']::text[], ARRAY['bodyweight']::text[], 'horizontal_push', 'bodyweight', true, 'bilateral', true, 'beginner'),
  ('tempo-push-up', 'Tempo Push-Up', 'chest', ARRAY['triceps','front_delts']::text[], ARRAY['bodyweight']::text[], 'horizontal_push', 'bodyweight', true, 'bilateral', true, 'beginner'),
  ('ring-push-up', 'Ring Push-Up', 'chest', ARRAY['triceps','front_delts']::text[], ARRAY['bodyweight']::text[], 'horizontal_push', 'bodyweight', true, 'bilateral', true, 'beginner'),
  ('archer-push-up', 'Archer Push-Up', 'chest', ARRAY['triceps','front_delts']::text[], ARRAY['bodyweight']::text[], 'horizontal_push', 'bodyweight', true, 'bilateral', true, 'beginner'),
  ('one-arm-push-up', 'One-Arm Push-Up', 'chest', ARRAY['triceps','front_delts']::text[], ARRAY['bodyweight']::text[], 'horizontal_push', 'bodyweight', true, 'bilateral', true, 'beginner'),
  ('weighted-push-up', 'Weighted Push-Up', 'chest', ARRAY['triceps','front_delts']::text[], ARRAY['bodyweight']::text[], 'horizontal_push', 'bodyweight', true, 'bilateral', true, 'beginner'),
  ('pull-up', 'Pull-Up', 'lats', ARRAY['biceps','upper_back']::text[], ARRAY['pull_up_bar','bodyweight']::text[], 'vertical_pull', 'bodyweight', false, 'bilateral', true, 'beginner'),
  ('wide-grip-pull-up', 'Wide-Grip Pull-Up', 'lats', ARRAY['biceps','upper_back']::text[], ARRAY['pull_up_bar','bodyweight']::text[], 'vertical_pull', 'bodyweight', false, 'bilateral', true, 'beginner'),
  ('neutral-grip-pull-up', 'Neutral-Grip Pull-Up', 'lats', ARRAY['biceps','upper_back']::text[], ARRAY['pull_up_bar','bodyweight']::text[], 'vertical_pull', 'bodyweight', false, 'bilateral', true, 'beginner'),
  ('commando-pull-up', 'Commando Pull-Up', 'lats', ARRAY['biceps','upper_back']::text[], ARRAY['pull_up_bar','bodyweight']::text[], 'vertical_pull', 'bodyweight', false, 'bilateral', true, 'beginner'),
  ('weighted-pull-up', 'Weighted Pull-Up', 'lats', ARRAY['biceps','upper_back']::text[], ARRAY['pull_up_bar','bodyweight']::text[], 'vertical_pull', 'bodyweight', false, 'bilateral', true, 'beginner'),
  ('assisted-pull-up', 'Assisted Pull-Up', 'lats', ARRAY['biceps','upper_back']::text[], ARRAY['pull_up_bar','bodyweight']::text[], 'vertical_pull', 'bodyweight', false, 'bilateral', true, 'beginner'),
  ('scapular-pull-up', 'Scapular Pull-Up', 'lats', ARRAY['biceps','upper_back']::text[], ARRAY['pull_up_bar','bodyweight']::text[], 'vertical_pull', 'bodyweight', false, 'bilateral', true, 'beginner'),
  ('sternum-pull-up', 'Sternum Pull-Up', 'lats', ARRAY['biceps','upper_back']::text[], ARRAY['pull_up_bar','bodyweight']::text[], 'vertical_pull', 'bodyweight', false, 'bilateral', true, 'beginner'),
  ('chin-up', 'Chin-Up', 'lats', ARRAY['biceps','upper_back']::text[], ARRAY['pull_up_bar','bodyweight']::text[], 'vertical_pull', 'bodyweight', false, 'bilateral', true, 'beginner'),
  ('close-grip-chin-up', 'Close-Grip Chin-Up', 'lats', ARRAY['biceps','upper_back']::text[], ARRAY['pull_up_bar','bodyweight']::text[], 'vertical_pull', 'bodyweight', false, 'bilateral', true, 'beginner'),
  ('weighted-chin-up', 'Weighted Chin-Up', 'lats', ARRAY['biceps','upper_back']::text[], ARRAY['pull_up_bar','bodyweight']::text[], 'vertical_pull', 'bodyweight', false, 'bilateral', true, 'beginner'),
  ('assisted-chin-up', 'Assisted Chin-Up', 'lats', ARRAY['biceps','upper_back']::text[], ARRAY['pull_up_bar','bodyweight']::text[], 'vertical_pull', 'bodyweight', false, 'bilateral', true, 'beginner'),
  ('wide-grip-lat-pulldown', 'Wide-Grip Lat Pulldown', 'lats', ARRAY['biceps','upper_back']::text[], ARRAY['cable']::text[], 'vertical_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('close-grip-lat-pulldown', 'Close-Grip Lat Pulldown', 'lats', ARRAY['biceps','upper_back']::text[], ARRAY['cable']::text[], 'vertical_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('neutral-grip-lat-pulldown', 'Neutral-Grip Lat Pulldown', 'lats', ARRAY['biceps','upper_back']::text[], ARRAY['cable']::text[], 'vertical_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('underhand-lat-pulldown', 'Underhand Lat Pulldown', 'lats', ARRAY['biceps','upper_back']::text[], ARRAY['cable']::text[], 'vertical_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('kneeling-lat-pulldown', 'Kneeling Lat Pulldown', 'lats', ARRAY['biceps','upper_back']::text[], ARRAY['cable']::text[], 'vertical_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('single-arm-lat-pulldown', 'Single-Arm Lat Pulldown', 'lats', ARRAY['biceps','upper_back']::text[], ARRAY['cable']::text[], 'vertical_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('half-kneeling-single-arm-lat-pulldown', 'Half-Kneeling Single-Arm Lat Pulldown', 'lats', ARRAY['biceps','upper_back']::text[], ARRAY['cable']::text[], 'vertical_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('machine-lat-pulldown', 'Machine Lat Pulldown', 'lats', ARRAY['biceps','upper_back']::text[], ARRAY['cable']::text[], 'vertical_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('seated-cable-row', 'Seated Cable Row', 'upper_back', ARRAY['lats','biceps','rear_delts']::text[], ARRAY['cable']::text[], 'horizontal_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('close-grip-cable-row', 'Close-Grip Cable Row', 'upper_back', ARRAY['lats','biceps','rear_delts']::text[], ARRAY['cable']::text[], 'horizontal_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('wide-grip-cable-row', 'Wide-Grip Cable Row', 'upper_back', ARRAY['lats','biceps','rear_delts']::text[], ARRAY['cable']::text[], 'horizontal_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('underhand-cable-row', 'Underhand Cable Row', 'upper_back', ARRAY['lats','biceps','rear_delts']::text[], ARRAY['cable']::text[], 'horizontal_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('rope-cable-row', 'Rope Cable Row', 'upper_back', ARRAY['lats','biceps','rear_delts']::text[], ARRAY['cable']::text[], 'horizontal_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('high-cable-row', 'High Cable Row', 'upper_back', ARRAY['lats','biceps','rear_delts']::text[], ARRAY['cable']::text[], 'horizontal_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('low-cable-row', 'Low Cable Row', 'upper_back', ARRAY['lats','biceps','rear_delts']::text[], ARRAY['cable']::text[], 'horizontal_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('single-arm-cable-row', 'Single-Arm Cable Row', 'upper_back', ARRAY['lats','biceps','rear_delts']::text[], ARRAY['cable']::text[], 'horizontal_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('half-kneeling-cable-row', 'Half-Kneeling Cable Row', 'upper_back', ARRAY['lats','biceps','rear_delts']::text[], ARRAY['cable']::text[], 'horizontal_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('one-arm-dumbbell-row', 'One-Arm Dumbbell Row', 'upper_back', ARRAY['lats','biceps','rear_delts']::text[], ARRAY['dumbbell','bench']::text[], 'horizontal_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('bench-supported-dumbbell-row', 'Bench-Supported Dumbbell Row', 'upper_back', ARRAY['lats','biceps','rear_delts']::text[], ARRAY['dumbbell','bench']::text[], 'horizontal_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('chest-supported-dumbbell-row', 'Chest-Supported Dumbbell Row', 'upper_back', ARRAY['lats','biceps','rear_delts']::text[], ARRAY['dumbbell','bench']::text[], 'horizontal_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('incline-dumbbell-row', 'Incline Dumbbell Row', 'upper_back', ARRAY['lats','biceps','rear_delts']::text[], ARRAY['dumbbell','bench']::text[], 'horizontal_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('dumbbell-seal-row', 'Dumbbell Seal Row', 'upper_back', ARRAY['lats','biceps','rear_delts']::text[], ARRAY['dumbbell','bench']::text[], 'horizontal_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('dumbbell-gorilla-row', 'Dumbbell Gorilla Row', 'upper_back', ARRAY['lats','biceps','rear_delts']::text[], ARRAY['dumbbell','bench']::text[], 'horizontal_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('renegade-row', 'Renegade Row', 'upper_back', ARRAY['lats','biceps','rear_delts']::text[], ARRAY['dumbbell','bench']::text[], 'horizontal_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('bent-over-barbell-row', 'Bent-Over Barbell Row', 'upper_back', ARRAY['lats','biceps','rear_delts']::text[], ARRAY['barbell']::text[], 'horizontal_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('pendlay-row', 'Pendlay Row', 'upper_back', ARRAY['lats','biceps','rear_delts']::text[], ARRAY['barbell']::text[], 'horizontal_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('underhand-barbell-row', 'Underhand Barbell Row', 'upper_back', ARRAY['lats','biceps','rear_delts']::text[], ARRAY['barbell']::text[], 'horizontal_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('wide-grip-barbell-row', 'Wide-Grip Barbell Row', 'upper_back', ARRAY['lats','biceps','rear_delts']::text[], ARRAY['barbell']::text[], 'horizontal_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('barbell-seal-row', 'Barbell Seal Row', 'upper_back', ARRAY['lats','biceps','rear_delts']::text[], ARRAY['barbell']::text[], 'horizontal_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('meadows-row', 'Meadows Row', 'upper_back', ARRAY['lats','biceps','rear_delts']::text[], ARRAY['barbell']::text[], 'horizontal_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('landmine-row', 'Landmine Row', 'upper_back', ARRAY['lats','biceps','rear_delts']::text[], ARRAY['barbell']::text[], 'horizontal_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('t-bar-row', 'T-Bar Row', 'upper_back', ARRAY['lats','biceps','rear_delts']::text[], ARRAY['barbell']::text[], 'horizontal_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('chest-supported-machine-row', 'Chest-Supported Machine Row', 'upper_back', ARRAY['lats','biceps','rear_delts']::text[], ARRAY['machine']::text[], 'horizontal_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('plate-loaded-row', 'Plate-Loaded Row', 'upper_back', ARRAY['lats','biceps','rear_delts']::text[], ARRAY['machine']::text[], 'horizontal_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('iso-lateral-machine-row', 'Iso-Lateral Machine Row', 'upper_back', ARRAY['lats','biceps','rear_delts']::text[], ARRAY['machine']::text[], 'horizontal_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('high-row-machine', 'High Row Machine', 'upper_back', ARRAY['lats','biceps','rear_delts']::text[], ARRAY['machine']::text[], 'horizontal_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('low-row-machine', 'Low Row Machine', 'upper_back', ARRAY['lats','biceps','rear_delts']::text[], ARRAY['machine']::text[], 'horizontal_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('single-arm-machine-row', 'Single-Arm Machine Row', 'upper_back', ARRAY['lats','biceps','rear_delts']::text[], ARRAY['machine']::text[], 'horizontal_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('dumbbell-pullover', 'Dumbbell Pullover', 'lats', ARRAY['triceps']::text[], ARRAY['cable']::text[], 'shoulder_extension', 'strength', true, 'bilateral', false, 'beginner'),
  ('cable-pullover', 'Cable Pullover', 'lats', ARRAY['triceps']::text[], ARRAY['cable']::text[], 'shoulder_extension', 'strength', true, 'bilateral', false, 'beginner'),
  ('straight-arm-cable-pulldown', 'Straight-Arm Cable Pulldown', 'lats', ARRAY['triceps']::text[], ARRAY['cable']::text[], 'shoulder_extension', 'strength', true, 'bilateral', false, 'beginner'),
  ('single-arm-straight-arm-pulldown', 'Single-Arm Straight-Arm Pulldown', 'lats', ARRAY['triceps']::text[], ARRAY['cable']::text[], 'shoulder_extension', 'strength', true, 'bilateral', false, 'beginner'),
  ('machine-pullover', 'Machine Pullover', 'lats', ARRAY['triceps']::text[], ARRAY['cable']::text[], 'shoulder_extension', 'strength', true, 'bilateral', false, 'beginner'),
  ('barbell-shrug', 'Barbell Shrug', 'traps', ARRAY['upper_back']::text[], ARRAY['barbell']::text[], 'carry', 'strength', false, 'bilateral', false, 'beginner'),
  ('dumbbell-shrug', 'Dumbbell Shrug', 'traps', ARRAY['upper_back']::text[], ARRAY['barbell']::text[], 'carry', 'strength', false, 'bilateral', false, 'beginner'),
  ('smith-machine-shrug', 'Smith Machine Shrug', 'traps', ARRAY['upper_back']::text[], ARRAY['barbell']::text[], 'carry', 'strength', false, 'bilateral', false, 'beginner'),
  ('cable-shrug', 'Cable Shrug', 'traps', ARRAY['upper_back']::text[], ARRAY['barbell']::text[], 'carry', 'strength', false, 'bilateral', false, 'beginner'),
  ('machine-shrug', 'Machine Shrug', 'traps', ARRAY['upper_back']::text[], ARRAY['barbell']::text[], 'carry', 'strength', false, 'bilateral', false, 'beginner'),
  ('behind-the-back-shrug', 'Behind-the-Back Shrug', 'traps', ARRAY['upper_back']::text[], ARRAY['barbell']::text[], 'carry', 'strength', false, 'bilateral', false, 'beginner'),
  ('back-extension', 'Back Extension', 'lower_back', ARRAY['glutes','hamstrings']::text[], ARRAY['bodyweight']::text[], 'hinge', 'bodyweight', false, 'bilateral', true, 'beginner'),
  ('45-degree-back-extension', '45-Degree Back Extension', 'lower_back', ARRAY['glutes','hamstrings']::text[], ARRAY['bodyweight']::text[], 'hinge', 'bodyweight', false, 'bilateral', true, 'beginner'),
  ('reverse-hyperextension', 'Reverse Hyperextension', 'lower_back', ARRAY['glutes','hamstrings']::text[], ARRAY['bodyweight']::text[], 'hinge', 'bodyweight', false, 'bilateral', true, 'beginner'),
  ('superman', 'Superman', 'lower_back', ARRAY['glutes','hamstrings']::text[], ARRAY['bodyweight']::text[], 'hinge', 'bodyweight', false, 'bilateral', true, 'beginner'),
  ('standing-barbell-overhead-press', 'Standing Barbell Overhead Press', 'front_delts', ARRAY['triceps','side_delts']::text[], ARRAY['barbell']::text[], 'vertical_push', 'strength', false, 'bilateral', false, 'intermediate'),
  ('seated-barbell-overhead-press', 'Seated Barbell Overhead Press', 'front_delts', ARRAY['triceps','side_delts']::text[], ARRAY['barbell']::text[], 'vertical_push', 'strength', false, 'bilateral', false, 'intermediate'),
  ('push-press', 'Push Press', 'front_delts', ARRAY['triceps','side_delts']::text[], ARRAY['barbell']::text[], 'vertical_push', 'strength', false, 'bilateral', false, 'intermediate'),
  ('behind-the-neck-press', 'Behind-the-Neck Press', 'front_delts', ARRAY['triceps','side_delts']::text[], ARRAY['barbell']::text[], 'vertical_push', 'strength', false, 'bilateral', false, 'intermediate'),
  ('z-press', 'Z Press', 'front_delts', ARRAY['triceps','side_delts']::text[], ARRAY['barbell']::text[], 'vertical_push', 'strength', false, 'bilateral', false, 'intermediate'),
  ('seated-dumbbell-shoulder-press', 'Seated Dumbbell Shoulder Press', 'front_delts', ARRAY['triceps','side_delts']::text[], ARRAY['dumbbell']::text[], 'vertical_push', 'strength', true, 'bilateral', false, 'beginner'),
  ('standing-dumbbell-shoulder-press', 'Standing Dumbbell Shoulder Press', 'front_delts', ARRAY['triceps','side_delts']::text[], ARRAY['dumbbell']::text[], 'vertical_push', 'strength', true, 'bilateral', false, 'beginner'),
  ('arnold-press', 'Arnold Press', 'front_delts', ARRAY['triceps','side_delts']::text[], ARRAY['dumbbell']::text[], 'vertical_push', 'strength', true, 'bilateral', false, 'beginner'),
  ('neutral-grip-dumbbell-shoulder-press', 'Neutral-Grip Dumbbell Shoulder Press', 'front_delts', ARRAY['triceps','side_delts']::text[], ARRAY['dumbbell']::text[], 'vertical_push', 'strength', true, 'bilateral', false, 'beginner'),
  ('single-arm-dumbbell-shoulder-press', 'Single-Arm Dumbbell Shoulder Press', 'front_delts', ARRAY['triceps','side_delts']::text[], ARRAY['dumbbell']::text[], 'vertical_push', 'strength', true, 'bilateral', false, 'beginner'),
  ('dumbbell-z-press', 'Dumbbell Z Press', 'front_delts', ARRAY['triceps','side_delts']::text[], ARRAY['dumbbell']::text[], 'vertical_push', 'strength', true, 'bilateral', false, 'beginner'),
  ('machine-shoulder-press', 'Machine Shoulder Press', 'front_delts', ARRAY['triceps','side_delts']::text[], ARRAY['machine']::text[], 'vertical_push', 'strength', true, 'bilateral', false, 'beginner'),
  ('plate-loaded-shoulder-press', 'Plate-Loaded Shoulder Press', 'front_delts', ARRAY['triceps','side_delts']::text[], ARRAY['machine']::text[], 'vertical_push', 'strength', true, 'bilateral', false, 'beginner'),
  ('smith-machine-shoulder-press', 'Smith Machine Shoulder Press', 'front_delts', ARRAY['triceps','side_delts']::text[], ARRAY['machine']::text[], 'vertical_push', 'strength', true, 'bilateral', false, 'beginner'),
  ('single-arm-machine-shoulder-press', 'Single-Arm Machine Shoulder Press', 'front_delts', ARRAY['triceps','side_delts']::text[], ARRAY['machine']::text[], 'vertical_push', 'strength', true, 'bilateral', false, 'beginner'),
  ('cable-lateral-raise', 'Cable Lateral Raise', 'side_delts', ARRAY['traps']::text[], ARRAY['dumbbell']::text[], 'shoulder_abduction', 'strength', true, 'bilateral', false, 'beginner'),
  ('behind-the-back-cable-lateral-raise', 'Behind-the-Back Cable Lateral Raise', 'side_delts', ARRAY['traps']::text[], ARRAY['dumbbell']::text[], 'shoulder_abduction', 'strength', true, 'bilateral', false, 'beginner'),
  ('leaning-cable-lateral-raise', 'Leaning Cable Lateral Raise', 'side_delts', ARRAY['traps']::text[], ARRAY['dumbbell']::text[], 'shoulder_abduction', 'strength', true, 'bilateral', false, 'beginner'),
  ('dumbbell-lateral-raise', 'Dumbbell Lateral Raise', 'side_delts', ARRAY['traps']::text[], ARRAY['dumbbell']::text[], 'shoulder_abduction', 'strength', true, 'bilateral', false, 'beginner'),
  ('seated-dumbbell-lateral-raise', 'Seated Dumbbell Lateral Raise', 'side_delts', ARRAY['traps']::text[], ARRAY['dumbbell']::text[], 'shoulder_abduction', 'strength', true, 'bilateral', false, 'beginner'),
  ('lean-away-dumbbell-lateral-raise', 'Lean-Away Dumbbell Lateral Raise', 'side_delts', ARRAY['traps']::text[], ARRAY['dumbbell']::text[], 'shoulder_abduction', 'strength', true, 'bilateral', false, 'beginner'),
  ('machine-lateral-raise', 'Machine Lateral Raise', 'side_delts', ARRAY['traps']::text[], ARRAY['dumbbell']::text[], 'shoulder_abduction', 'strength', true, 'bilateral', false, 'beginner'),
  ('single-arm-machine-lateral-raise', 'Single-Arm Machine Lateral Raise', 'side_delts', ARRAY['traps']::text[], ARRAY['dumbbell']::text[], 'shoulder_abduction', 'strength', true, 'bilateral', false, 'beginner'),
  ('plate-lateral-raise', 'Plate Lateral Raise', 'side_delts', ARRAY['traps']::text[], ARRAY['dumbbell']::text[], 'shoulder_abduction', 'strength', true, 'bilateral', false, 'beginner'),
  ('dumbbell-front-raise', 'Dumbbell Front Raise', 'front_delts', ARRAY[]::text[], ARRAY['dumbbell']::text[], 'shoulder_flexion', 'strength', true, 'bilateral', false, 'beginner'),
  ('alternating-dumbbell-front-raise', 'Alternating Dumbbell Front Raise', 'front_delts', ARRAY[]::text[], ARRAY['dumbbell']::text[], 'shoulder_flexion', 'strength', true, 'bilateral', false, 'beginner'),
  ('cable-front-raise', 'Cable Front Raise', 'front_delts', ARRAY[]::text[], ARRAY['dumbbell']::text[], 'shoulder_flexion', 'strength', true, 'bilateral', false, 'beginner'),
  ('plate-front-raise', 'Plate Front Raise', 'front_delts', ARRAY[]::text[], ARRAY['dumbbell']::text[], 'shoulder_flexion', 'strength', true, 'bilateral', false, 'beginner'),
  ('barbell-front-raise', 'Barbell Front Raise', 'front_delts', ARRAY[]::text[], ARRAY['dumbbell']::text[], 'shoulder_flexion', 'strength', true, 'bilateral', false, 'beginner'),
  ('reverse-pec-deck', 'Reverse Pec Deck', 'rear_delts', ARRAY['upper_back','traps']::text[], ARRAY['cable']::text[], 'horizontal_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('bent-over-dumbbell-rear-delt-raise', 'Bent-Over Dumbbell Rear Delt Raise', 'rear_delts', ARRAY['upper_back','traps']::text[], ARRAY['cable']::text[], 'horizontal_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('chest-supported-rear-delt-raise', 'Chest-Supported Rear Delt Raise', 'rear_delts', ARRAY['upper_back','traps']::text[], ARRAY['cable']::text[], 'horizontal_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('cable-rear-delt-fly', 'Cable Rear Delt Fly', 'rear_delts', ARRAY['upper_back','traps']::text[], ARRAY['cable']::text[], 'horizontal_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('single-arm-cable-rear-delt-fly', 'Single-Arm Cable Rear Delt Fly', 'rear_delts', ARRAY['upper_back','traps']::text[], ARRAY['cable']::text[], 'horizontal_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('face-pull', 'Face Pull', 'rear_delts', ARRAY['upper_back','traps']::text[], ARRAY['cable']::text[], 'horizontal_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('cable-face-pull-with-external-rotation', 'Cable Face Pull with External Rotation', 'rear_delts', ARRAY['upper_back','traps']::text[], ARRAY['cable']::text[], 'horizontal_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('band-pull-apart', 'Band Pull-Apart', 'rear_delts', ARRAY['upper_back','traps']::text[], ARRAY['cable']::text[], 'horizontal_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('pike-push-up', 'Pike Push-Up', 'front_delts', ARRAY['triceps','side_delts']::text[], ARRAY['bodyweight']::text[], 'vertical_push', 'bodyweight', false, 'bilateral', true, 'intermediate'),
  ('feet-elevated-pike-push-up', 'Feet-Elevated Pike Push-Up', 'front_delts', ARRAY['triceps','side_delts']::text[], ARRAY['bodyweight']::text[], 'vertical_push', 'bodyweight', false, 'bilateral', true, 'intermediate'),
  ('wall-handstand-push-up', 'Wall Handstand Push-Up', 'front_delts', ARRAY['triceps','side_delts']::text[], ARRAY['bodyweight']::text[], 'vertical_push', 'bodyweight', false, 'bilateral', true, 'intermediate'),
  ('handstand-push-up', 'Handstand Push-Up', 'front_delts', ARRAY['triceps','side_delts']::text[], ARRAY['bodyweight']::text[], 'vertical_push', 'bodyweight', false, 'bilateral', true, 'intermediate'),
  ('wall-walk', 'Wall Walk', 'front_delts', ARRAY['triceps','side_delts']::text[], ARRAY['bodyweight']::text[], 'vertical_push', 'bodyweight', false, 'bilateral', true, 'intermediate'),
  ('standing-barbell-curl', 'Standing Barbell Curl', 'biceps', ARRAY['forearms']::text[], ARRAY['barbell']::text[], 'elbow_flexion', 'strength', false, 'bilateral', false, 'beginner'),
  ('wide-grip-barbell-curl', 'Wide-Grip Barbell Curl', 'biceps', ARRAY['forearms']::text[], ARRAY['barbell']::text[], 'elbow_flexion', 'strength', false, 'bilateral', false, 'beginner'),
  ('close-grip-barbell-curl', 'Close-Grip Barbell Curl', 'biceps', ARRAY['forearms']::text[], ARRAY['barbell']::text[], 'elbow_flexion', 'strength', false, 'bilateral', false, 'beginner'),
  ('barbell-drag-curl', 'Barbell Drag Curl', 'biceps', ARRAY['forearms']::text[], ARRAY['barbell']::text[], 'elbow_flexion', 'strength', false, 'bilateral', false, 'beginner'),
  ('spider-barbell-curl', 'Spider Barbell Curl', 'biceps', ARRAY['forearms']::text[], ARRAY['barbell']::text[], 'elbow_flexion', 'strength', false, 'bilateral', false, 'beginner'),
  ('ez-bar-curl', 'EZ-Bar Curl', 'biceps', ARRAY['forearms']::text[], ARRAY['ez_bar']::text[], 'elbow_flexion', 'strength', false, 'bilateral', false, 'beginner'),
  ('wide-grip-ez-bar-curl', 'Wide-Grip EZ-Bar Curl', 'biceps', ARRAY['forearms']::text[], ARRAY['ez_bar']::text[], 'elbow_flexion', 'strength', false, 'bilateral', false, 'beginner'),
  ('close-grip-ez-bar-curl', 'Close-Grip EZ-Bar Curl', 'biceps', ARRAY['forearms']::text[], ARRAY['ez_bar']::text[], 'elbow_flexion', 'strength', false, 'bilateral', false, 'beginner'),
  ('ez-bar-preacher-curl', 'EZ-Bar Preacher Curl', 'biceps', ARRAY['forearms']::text[], ARRAY['ez_bar']::text[], 'elbow_flexion', 'strength', false, 'bilateral', false, 'beginner'),
  ('ez-bar-reverse-curl', 'EZ-Bar Reverse Curl', 'biceps', ARRAY['forearms']::text[], ARRAY['ez_bar']::text[], 'elbow_flexion', 'strength', false, 'bilateral', false, 'beginner'),
  ('ez-bar-spider-curl', 'EZ-Bar Spider Curl', 'biceps', ARRAY['forearms']::text[], ARRAY['ez_bar']::text[], 'elbow_flexion', 'strength', false, 'bilateral', false, 'beginner'),
  ('standing-dumbbell-curl', 'Standing Dumbbell Curl', 'biceps', ARRAY['forearms']::text[], ARRAY['dumbbell']::text[], 'elbow_flexion', 'strength', true, 'bilateral', false, 'beginner'),
  ('alternating-dumbbell-curl', 'Alternating Dumbbell Curl', 'biceps', ARRAY['forearms']::text[], ARRAY['dumbbell']::text[], 'elbow_flexion', 'strength', true, 'bilateral', false, 'beginner'),
  ('seated-dumbbell-curl', 'Seated Dumbbell Curl', 'biceps', ARRAY['forearms']::text[], ARRAY['dumbbell']::text[], 'elbow_flexion', 'strength', true, 'bilateral', false, 'beginner'),
  ('incline-dumbbell-curl', 'Incline Dumbbell Curl', 'biceps', ARRAY['forearms']::text[], ARRAY['dumbbell']::text[], 'elbow_flexion', 'strength', true, 'bilateral', false, 'beginner'),
  ('dumbbell-preacher-curl', 'Dumbbell Preacher Curl', 'biceps', ARRAY['forearms']::text[], ARRAY['dumbbell']::text[], 'elbow_flexion', 'strength', true, 'bilateral', false, 'beginner'),
  ('concentration-curl', 'Concentration Curl', 'biceps', ARRAY['forearms']::text[], ARRAY['dumbbell']::text[], 'elbow_flexion', 'strength', true, 'bilateral', false, 'beginner'),
  ('spider-dumbbell-curl', 'Spider Dumbbell Curl', 'biceps', ARRAY['forearms']::text[], ARRAY['dumbbell']::text[], 'elbow_flexion', 'strength', true, 'bilateral', false, 'beginner'),
  ('cross-body-curl', 'Cross-Body Curl', 'biceps', ARRAY['forearms']::text[], ARRAY['dumbbell']::text[], 'elbow_flexion', 'strength', true, 'bilateral', false, 'beginner'),
  ('dumbbell-hammer-curl', 'Dumbbell Hammer Curl', 'biceps', ARRAY['forearms']::text[], ARRAY['dumbbell']::text[], 'elbow_flexion', 'strength', true, 'bilateral', false, 'beginner'),
  ('incline-hammer-curl', 'Incline Hammer Curl', 'biceps', ARRAY['forearms']::text[], ARRAY['dumbbell']::text[], 'elbow_flexion', 'strength', true, 'bilateral', false, 'beginner'),
  ('zottman-curl', 'Zottman Curl', 'biceps', ARRAY['forearms']::text[], ARRAY['dumbbell']::text[], 'elbow_flexion', 'strength', true, 'bilateral', false, 'beginner'),
  ('bayesian-dumbbell-curl', 'Bayesian Dumbbell Curl', 'biceps', ARRAY['forearms']::text[], ARRAY['dumbbell']::text[], 'elbow_flexion', 'strength', true, 'bilateral', false, 'beginner'),
  ('straight-bar-cable-curl', 'Straight-Bar Cable Curl', 'biceps', ARRAY['forearms']::text[], ARRAY['cable']::text[], 'elbow_flexion', 'strength', true, 'bilateral', false, 'beginner'),
  ('rope-cable-curl', 'Rope Cable Curl', 'biceps', ARRAY['forearms']::text[], ARRAY['cable']::text[], 'elbow_flexion', 'strength', true, 'bilateral', false, 'beginner'),
  ('bayesian-cable-curl', 'Bayesian Cable Curl', 'biceps', ARRAY['forearms']::text[], ARRAY['cable']::text[], 'elbow_flexion', 'strength', true, 'bilateral', false, 'beginner'),
  ('high-cable-curl', 'High Cable Curl', 'biceps', ARRAY['forearms']::text[], ARRAY['cable']::text[], 'elbow_flexion', 'strength', true, 'bilateral', false, 'beginner'),
  ('lying-cable-curl', 'Lying Cable Curl', 'biceps', ARRAY['forearms']::text[], ARRAY['cable']::text[], 'elbow_flexion', 'strength', true, 'bilateral', false, 'beginner'),
  ('cable-preacher-curl', 'Cable Preacher Curl', 'biceps', ARRAY['forearms']::text[], ARRAY['cable']::text[], 'elbow_flexion', 'strength', true, 'bilateral', false, 'beginner'),
  ('single-arm-cable-curl', 'Single-Arm Cable Curl', 'biceps', ARRAY['forearms']::text[], ARRAY['cable']::text[], 'elbow_flexion', 'strength', true, 'bilateral', false, 'beginner'),
  ('single-arm-hammer-cable-curl', 'Single-Arm Hammer Cable Curl', 'biceps', ARRAY['forearms']::text[], ARRAY['cable']::text[], 'elbow_flexion', 'strength', true, 'bilateral', false, 'beginner'),
  ('machine-biceps-curl', 'Machine Biceps Curl', 'biceps', ARRAY['forearms']::text[], ARRAY['machine']::text[], 'elbow_flexion', 'strength', true, 'bilateral', false, 'beginner'),
  ('machine-preacher-curl', 'Machine Preacher Curl', 'biceps', ARRAY['forearms']::text[], ARRAY['machine']::text[], 'elbow_flexion', 'strength', true, 'bilateral', false, 'beginner'),
  ('single-arm-machine-curl', 'Single-Arm Machine Curl', 'biceps', ARRAY['forearms']::text[], ARRAY['machine']::text[], 'elbow_flexion', 'strength', true, 'bilateral', false, 'beginner'),
  ('cable-triceps-pushdown', 'Cable Triceps Pushdown', 'triceps', ARRAY[]::text[], ARRAY['cable']::text[], 'elbow_extension', 'strength', true, 'bilateral', false, 'beginner'),
  ('rope-triceps-pushdown', 'Rope Triceps Pushdown', 'triceps', ARRAY[]::text[], ARRAY['cable']::text[], 'elbow_extension', 'strength', true, 'bilateral', false, 'beginner'),
  ('reverse-grip-pushdown', 'Reverse-Grip Pushdown', 'triceps', ARRAY[]::text[], ARRAY['cable']::text[], 'elbow_extension', 'strength', true, 'bilateral', false, 'beginner'),
  ('single-arm-cable-pushdown', 'Single-Arm Cable Pushdown', 'triceps', ARRAY[]::text[], ARRAY['cable']::text[], 'elbow_extension', 'strength', true, 'bilateral', false, 'beginner'),
  ('cross-body-cable-extension', 'Cross-Body Cable Extension', 'triceps', ARRAY[]::text[], ARRAY['cable']::text[], 'elbow_extension', 'strength', true, 'bilateral', false, 'beginner'),
  ('cable-kickback', 'Cable Kickback', 'triceps', ARRAY[]::text[], ARRAY['cable']::text[], 'elbow_extension', 'strength', true, 'bilateral', false, 'beginner'),
  ('overhead-rope-triceps-extension', 'Overhead Rope Triceps Extension', 'triceps', ARRAY[]::text[], ARRAY['cable']::text[], 'elbow_extension', 'strength', true, 'bilateral', false, 'beginner'),
  ('single-arm-overhead-cable-extension', 'Single-Arm Overhead Cable Extension', 'triceps', ARRAY[]::text[], ARRAY['cable']::text[], 'elbow_extension', 'strength', true, 'bilateral', false, 'beginner'),
  ('standing-cable-french-press', 'Standing Cable French Press', 'triceps', ARRAY[]::text[], ARRAY['cable']::text[], 'elbow_extension', 'strength', true, 'bilateral', false, 'beginner'),
  ('lying-cable-triceps-extension', 'Lying Cable Triceps Extension', 'triceps', ARRAY[]::text[], ARRAY['cable']::text[], 'elbow_extension', 'strength', true, 'bilateral', false, 'beginner'),
  ('ez-bar-skull-crusher', 'EZ-Bar Skull Crusher', 'triceps', ARRAY['chest','front_delts']::text[], ARRAY['ez_bar','bench']::text[], 'elbow_extension', 'strength', false, 'bilateral', false, 'beginner'),
  ('barbell-skull-crusher', 'Barbell Skull Crusher', 'triceps', ARRAY['chest','front_delts']::text[], ARRAY['ez_bar','bench']::text[], 'elbow_extension', 'strength', false, 'bilateral', false, 'beginner'),
  ('incline-skull-crusher', 'Incline Skull Crusher', 'triceps', ARRAY['chest','front_delts']::text[], ARRAY['ez_bar','bench']::text[], 'elbow_extension', 'strength', false, 'bilateral', false, 'beginner'),
  ('decline-skull-crusher', 'Decline Skull Crusher', 'triceps', ARRAY['chest','front_delts']::text[], ARRAY['ez_bar','bench']::text[], 'elbow_extension', 'strength', false, 'bilateral', false, 'beginner'),
  ('jm-press', 'JM Press', 'triceps', ARRAY['chest','front_delts']::text[], ARRAY['ez_bar','bench']::text[], 'elbow_extension', 'strength', false, 'bilateral', false, 'beginner'),
  ('close-grip-bench-press', 'Close-Grip Bench Press', 'triceps', ARRAY['chest','front_delts']::text[], ARRAY['ez_bar','bench']::text[], 'elbow_extension', 'strength', false, 'bilateral', false, 'beginner'),
  ('dumbbell-skull-crusher', 'Dumbbell Skull Crusher', 'triceps', ARRAY[]::text[], ARRAY['dumbbell']::text[], 'elbow_extension', 'strength', true, 'bilateral', false, 'beginner'),
  ('dumbbell-overhead-triceps-extension', 'Dumbbell Overhead Triceps Extension', 'triceps', ARRAY[]::text[], ARRAY['dumbbell']::text[], 'elbow_extension', 'strength', true, 'bilateral', false, 'beginner'),
  ('single-arm-dumbbell-overhead-extension', 'Single-Arm Dumbbell Overhead Extension', 'triceps', ARRAY[]::text[], ARRAY['dumbbell']::text[], 'elbow_extension', 'strength', true, 'bilateral', false, 'beginner'),
  ('dumbbell-tate-press', 'Dumbbell Tate Press', 'triceps', ARRAY[]::text[], ARRAY['dumbbell']::text[], 'elbow_extension', 'strength', true, 'bilateral', false, 'beginner'),
  ('dumbbell-kickback', 'Dumbbell Kickback', 'triceps', ARRAY[]::text[], ARRAY['dumbbell']::text[], 'elbow_extension', 'strength', true, 'bilateral', false, 'beginner'),
  ('parallel-bar-dip', 'Parallel-Bar Dip', 'triceps', ARRAY['chest','front_delts']::text[], ARRAY['bodyweight']::text[], 'elbow_extension', 'bodyweight', false, 'bilateral', true, 'beginner'),
  ('weighted-dip', 'Weighted Dip', 'triceps', ARRAY['chest','front_delts']::text[], ARRAY['bodyweight']::text[], 'elbow_extension', 'bodyweight', false, 'bilateral', true, 'beginner'),
  ('assisted-dip', 'Assisted Dip', 'triceps', ARRAY['chest','front_delts']::text[], ARRAY['bodyweight']::text[], 'elbow_extension', 'bodyweight', false, 'bilateral', true, 'beginner'),
  ('bench-dip', 'Bench Dip', 'triceps', ARRAY['chest','front_delts']::text[], ARRAY['bodyweight']::text[], 'elbow_extension', 'bodyweight', false, 'bilateral', true, 'beginner'),
  ('ring-dip', 'Ring Dip', 'triceps', ARRAY['chest','front_delts']::text[], ARRAY['bodyweight']::text[], 'elbow_extension', 'bodyweight', false, 'bilateral', true, 'beginner'),
  ('close-grip-push-up', 'Close-Grip Push-Up', 'triceps', ARRAY['chest','front_delts']::text[], ARRAY['bodyweight']::text[], 'elbow_extension', 'bodyweight', false, 'bilateral', true, 'beginner'),
  ('diamond-push-up', 'Diamond Push-Up', 'triceps', ARRAY['chest','front_delts']::text[], ARRAY['bodyweight']::text[], 'elbow_extension', 'bodyweight', false, 'bilateral', true, 'beginner'),
  ('high-bar-back-squat', 'High-Bar Back Squat', 'quads', ARRAY['glutes','adductors','lower_back']::text[], ARRAY['barbell']::text[], 'squat', 'strength', false, 'bilateral', false, 'intermediate'),
  ('low-bar-back-squat', 'Low-Bar Back Squat', 'quads', ARRAY['glutes','adductors','lower_back']::text[], ARRAY['barbell']::text[], 'squat', 'strength', false, 'bilateral', false, 'intermediate'),
  ('front-squat', 'Front Squat', 'quads', ARRAY['glutes','adductors','lower_back']::text[], ARRAY['barbell']::text[], 'squat', 'strength', false, 'bilateral', false, 'intermediate'),
  ('pause-squat', 'Pause Squat', 'quads', ARRAY['glutes','adductors','lower_back']::text[], ARRAY['barbell']::text[], 'squat', 'strength', false, 'bilateral', false, 'intermediate'),
  ('box-squat', 'Box Squat', 'quads', ARRAY['glutes','adductors','lower_back']::text[], ARRAY['barbell']::text[], 'squat', 'strength', false, 'bilateral', false, 'intermediate'),
  ('zercher-squat', 'Zercher Squat', 'quads', ARRAY['glutes','adductors','lower_back']::text[], ARRAY['barbell']::text[], 'squat', 'strength', false, 'bilateral', false, 'intermediate'),
  ('overhead-squat', 'Overhead Squat', 'quads', ARRAY['glutes','adductors','lower_back']::text[], ARRAY['barbell']::text[], 'squat', 'strength', false, 'bilateral', false, 'intermediate'),
  ('safety-bar-squat', 'Safety-Bar Squat', 'quads', ARRAY['glutes','adductors','lower_back']::text[], ARRAY['barbell']::text[], 'squat', 'strength', false, 'bilateral', false, 'intermediate'),
  ('goblet-squat', 'Goblet Squat', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['dumbbell']::text[], 'squat', 'strength', false, 'bilateral', false, 'beginner'),
  ('dumbbell-squat', 'Dumbbell Squat', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['dumbbell']::text[], 'squat', 'strength', false, 'bilateral', false, 'beginner'),
  ('double-dumbbell-front-squat', 'Double-Dumbbell Front Squat', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['dumbbell']::text[], 'squat', 'strength', false, 'bilateral', false, 'beginner'),
  ('dumbbell-sumo-squat', 'Dumbbell Sumo Squat', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['dumbbell']::text[], 'squat', 'strength', false, 'bilateral', false, 'beginner'),
  ('smith-machine-squat', 'Smith Machine Squat', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['smith_machine']::text[], 'squat', 'strength', false, 'bilateral', false, 'beginner'),
  ('smith-machine-front-squat', 'Smith Machine Front Squat', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['smith_machine']::text[], 'squat', 'strength', false, 'bilateral', false, 'beginner'),
  ('smith-machine-hack-squat', 'Smith Machine Hack Squat', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['smith_machine']::text[], 'squat', 'strength', false, 'bilateral', false, 'beginner'),
  ('smith-machine-sissy-squat', 'Smith Machine Sissy Squat', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['smith_machine']::text[], 'squat', 'strength', false, 'bilateral', false, 'beginner'),
  ('hack-squat', 'Hack Squat', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['machine']::text[], 'squat', 'strength', false, 'bilateral', false, 'beginner'),
  ('pendulum-squat', 'Pendulum Squat', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['machine']::text[], 'squat', 'strength', false, 'bilateral', false, 'beginner'),
  ('belt-squat', 'Belt Squat', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['machine']::text[], 'squat', 'strength', false, 'bilateral', false, 'beginner'),
  ('v-squat', 'V-Squat', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['machine']::text[], 'squat', 'strength', false, 'bilateral', false, 'beginner'),
  ('machine-squat', 'Machine Squat', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['machine']::text[], 'squat', 'strength', false, 'bilateral', false, 'beginner'),
  ('sissy-squat-machine', 'Sissy Squat Machine', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['machine']::text[], 'squat', 'strength', false, 'bilateral', false, 'beginner'),
  ('45-degree-leg-press', '45-Degree Leg Press', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['machine']::text[], 'squat', 'strength', true, 'bilateral', false, 'beginner'),
  ('horizontal-leg-press', 'Horizontal Leg Press', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['machine']::text[], 'squat', 'strength', true, 'bilateral', false, 'beginner'),
  ('vertical-leg-press', 'Vertical Leg Press', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['machine']::text[], 'squat', 'strength', true, 'bilateral', false, 'beginner'),
  ('decline-leg-press', 'Decline Leg Press', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['machine']::text[], 'squat', 'strength', true, 'bilateral', false, 'beginner'),
  ('wide-stance-leg-press', 'Wide-Stance Leg Press', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['machine']::text[], 'squat', 'strength', true, 'bilateral', false, 'beginner'),
  ('narrow-stance-leg-press', 'Narrow-Stance Leg Press', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['machine']::text[], 'squat', 'strength', true, 'bilateral', false, 'beginner'),
  ('single-leg-press', 'Single-Leg Press', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['machine']::text[], 'squat', 'strength', true, 'bilateral', false, 'beginner'),
  ('bulgarian-split-squat', 'Bulgarian Split Squat', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['dumbbell']::text[], 'lunge', 'strength', true, 'unilateral', false, 'beginner'),
  ('front-foot-elevated-split-squat', 'Front-Foot-Elevated Split Squat', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['dumbbell']::text[], 'lunge', 'strength', true, 'unilateral', false, 'beginner'),
  ('rear-foot-elevated-split-squat', 'Rear-Foot-Elevated Split Squat', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['dumbbell']::text[], 'lunge', 'strength', true, 'unilateral', false, 'beginner'),
  ('dumbbell-split-squat', 'Dumbbell Split Squat', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['dumbbell']::text[], 'lunge', 'strength', true, 'unilateral', false, 'beginner'),
  ('smith-machine-split-squat', 'Smith Machine Split Squat', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['dumbbell']::text[], 'lunge', 'strength', true, 'unilateral', false, 'beginner'),
  ('walking-lunge', 'Walking Lunge', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['dumbbell']::text[], 'lunge', 'strength', true, 'unilateral', false, 'beginner'),
  ('reverse-lunge', 'Reverse Lunge', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['dumbbell']::text[], 'lunge', 'strength', true, 'unilateral', false, 'beginner'),
  ('forward-lunge', 'Forward Lunge', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['dumbbell']::text[], 'lunge', 'strength', true, 'unilateral', false, 'beginner'),
  ('lateral-lunge', 'Lateral Lunge', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['dumbbell']::text[], 'lunge', 'strength', true, 'unilateral', false, 'beginner'),
  ('curtsy-lunge', 'Curtsy Lunge', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['dumbbell']::text[], 'lunge', 'strength', true, 'unilateral', false, 'beginner'),
  ('deficit-reverse-lunge', 'Deficit Reverse Lunge', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['dumbbell']::text[], 'lunge', 'strength', true, 'unilateral', false, 'beginner'),
  ('step-up', 'Step-Up', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['dumbbell']::text[], 'lunge', 'strength', true, 'unilateral', false, 'beginner'),
  ('lateral-step-up', 'Lateral Step-Up', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['dumbbell']::text[], 'lunge', 'strength', true, 'unilateral', false, 'beginner'),
  ('bodyweight-squat', 'Bodyweight Squat', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['bodyweight']::text[], 'squat', 'bodyweight', true, 'bilateral', true, 'beginner'),
  ('tempo-bodyweight-squat', 'Tempo Bodyweight Squat', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['bodyweight']::text[], 'squat', 'bodyweight', true, 'bilateral', true, 'beginner'),
  ('jump-squat', 'Jump Squat', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['bodyweight']::text[], 'squat', 'bodyweight', true, 'bilateral', true, 'beginner'),
  ('pistol-squat', 'Pistol Squat', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['bodyweight']::text[], 'squat', 'bodyweight', true, 'bilateral', true, 'beginner'),
  ('assisted-pistol-squat', 'Assisted Pistol Squat', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['bodyweight']::text[], 'squat', 'bodyweight', true, 'bilateral', true, 'beginner'),
  ('cossack-squat', 'Cossack Squat', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['bodyweight']::text[], 'squat', 'bodyweight', true, 'bilateral', true, 'beginner'),
  ('bodyweight-reverse-lunge', 'Bodyweight Reverse Lunge', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['bodyweight']::text[], 'squat', 'bodyweight', true, 'bilateral', true, 'beginner'),
  ('bodyweight-walking-lunge', 'Bodyweight Walking Lunge', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['bodyweight']::text[], 'squat', 'bodyweight', true, 'bilateral', true, 'beginner'),
  ('leg-extension', 'Leg Extension', 'quads', ARRAY[]::text[], ARRAY['machine']::text[], 'knee_extension', 'strength', true, 'bilateral', false, 'beginner'),
  ('single-leg-extension', 'Single-Leg Extension', 'quads', ARRAY[]::text[], ARRAY['machine']::text[], 'knee_extension', 'strength', true, 'bilateral', false, 'beginner'),
  ('sissy-squat', 'Sissy Squat', 'quads', ARRAY[]::text[], ARRAY['machine']::text[], 'knee_extension', 'strength', true, 'bilateral', false, 'beginner'),
  ('seated-leg-curl', 'Seated Leg Curl', 'hamstrings', ARRAY['calves']::text[], ARRAY['machine']::text[], 'knee_flexion', 'strength', true, 'bilateral', false, 'beginner'),
  ('lying-leg-curl', 'Lying Leg Curl', 'hamstrings', ARRAY['calves']::text[], ARRAY['machine']::text[], 'knee_flexion', 'strength', true, 'bilateral', false, 'beginner'),
  ('standing-leg-curl', 'Standing Leg Curl', 'hamstrings', ARRAY['calves']::text[], ARRAY['machine']::text[], 'knee_flexion', 'strength', true, 'bilateral', false, 'beginner'),
  ('single-leg-curl', 'Single-Leg Curl', 'hamstrings', ARRAY['calves']::text[], ARRAY['machine']::text[], 'knee_flexion', 'strength', true, 'bilateral', false, 'beginner'),
  ('nordic-hamstring-curl', 'Nordic Hamstring Curl', 'hamstrings', ARRAY['calves']::text[], ARRAY['machine']::text[], 'knee_flexion', 'strength', true, 'bilateral', false, 'beginner'),
  ('assisted-nordic-curl', 'Assisted Nordic Curl', 'hamstrings', ARRAY['calves']::text[], ARRAY['machine']::text[], 'knee_flexion', 'strength', true, 'bilateral', false, 'beginner'),
  ('sliding-leg-curl', 'Sliding Leg Curl', 'hamstrings', ARRAY['calves']::text[], ARRAY['machine']::text[], 'knee_flexion', 'strength', true, 'bilateral', false, 'beginner'),
  ('stability-ball-leg-curl', 'Stability-Ball Leg Curl', 'hamstrings', ARRAY['calves']::text[], ARRAY['machine']::text[], 'knee_flexion', 'strength', true, 'bilateral', false, 'beginner'),
  ('barbell-romanian-deadlift', 'Barbell Romanian Deadlift', 'hamstrings', ARRAY['glutes','lower_back']::text[], ARRAY['barbell']::text[], 'hinge', 'strength', true, 'bilateral', false, 'beginner'),
  ('dumbbell-romanian-deadlift', 'Dumbbell Romanian Deadlift', 'hamstrings', ARRAY['glutes','lower_back']::text[], ARRAY['barbell']::text[], 'hinge', 'strength', true, 'bilateral', false, 'beginner'),
  ('single-leg-romanian-deadlift', 'Single-Leg Romanian Deadlift', 'hamstrings', ARRAY['glutes','lower_back']::text[], ARRAY['barbell']::text[], 'hinge', 'strength', true, 'bilateral', false, 'beginner'),
  ('b-stance-romanian-deadlift', 'B-Stance Romanian Deadlift', 'hamstrings', ARRAY['glutes','lower_back']::text[], ARRAY['barbell']::text[], 'hinge', 'strength', true, 'bilateral', false, 'beginner'),
  ('stiff-leg-deadlift', 'Stiff-Leg Deadlift', 'hamstrings', ARRAY['glutes','lower_back']::text[], ARRAY['barbell']::text[], 'hinge', 'strength', true, 'bilateral', false, 'beginner'),
  ('good-morning', 'Good Morning', 'hamstrings', ARRAY['glutes','lower_back']::text[], ARRAY['barbell']::text[], 'hinge', 'strength', true, 'bilateral', false, 'beginner'),
  ('cable-pull-through', 'Cable Pull-Through', 'hamstrings', ARRAY['glutes','lower_back']::text[], ARRAY['barbell']::text[], 'hinge', 'strength', true, 'bilateral', false, 'beginner'),
  ('conventional-deadlift', 'Conventional Deadlift', 'glutes', ARRAY['hamstrings','lower_back','traps']::text[], ARRAY['barbell']::text[], 'hinge', 'strength', false, 'bilateral', false, 'intermediate'),
  ('sumo-deadlift', 'Sumo Deadlift', 'glutes', ARRAY['hamstrings','lower_back','traps']::text[], ARRAY['barbell']::text[], 'hinge', 'strength', false, 'bilateral', false, 'intermediate'),
  ('trap-bar-deadlift', 'Trap-Bar Deadlift', 'glutes', ARRAY['hamstrings','lower_back','traps']::text[], ARRAY['barbell']::text[], 'hinge', 'strength', false, 'bilateral', false, 'intermediate'),
  ('deficit-deadlift', 'Deficit Deadlift', 'glutes', ARRAY['hamstrings','lower_back','traps']::text[], ARRAY['barbell']::text[], 'hinge', 'strength', false, 'bilateral', false, 'intermediate'),
  ('rack-pull', 'Rack Pull', 'glutes', ARRAY['hamstrings','lower_back','traps']::text[], ARRAY['barbell']::text[], 'hinge', 'strength', false, 'bilateral', false, 'intermediate'),
  ('snatch-grip-deadlift', 'Snatch-Grip Deadlift', 'glutes', ARRAY['hamstrings','lower_back','traps']::text[], ARRAY['barbell']::text[], 'hinge', 'strength', false, 'bilateral', false, 'intermediate'),
  ('barbell-hip-thrust', 'Barbell Hip Thrust', 'glutes', ARRAY['hamstrings']::text[], ARRAY['bench']::text[], 'hip_extension', 'strength', true, 'bilateral', false, 'beginner'),
  ('smith-machine-hip-thrust', 'Smith Machine Hip Thrust', 'glutes', ARRAY['hamstrings']::text[], ARRAY['bench']::text[], 'hip_extension', 'strength', true, 'bilateral', false, 'beginner'),
  ('machine-hip-thrust', 'Machine Hip Thrust', 'glutes', ARRAY['hamstrings']::text[], ARRAY['bench']::text[], 'hip_extension', 'strength', true, 'bilateral', false, 'beginner'),
  ('single-leg-hip-thrust', 'Single-Leg Hip Thrust', 'glutes', ARRAY['hamstrings']::text[], ARRAY['bench']::text[], 'hip_extension', 'strength', true, 'bilateral', false, 'beginner'),
  ('dumbbell-hip-thrust', 'Dumbbell Hip Thrust', 'glutes', ARRAY['hamstrings']::text[], ARRAY['bench']::text[], 'hip_extension', 'strength', true, 'bilateral', false, 'beginner'),
  ('barbell-glute-bridge', 'Barbell Glute Bridge', 'glutes', ARRAY['hamstrings']::text[], ARRAY['bench']::text[], 'hip_extension', 'strength', true, 'bilateral', false, 'beginner'),
  ('dumbbell-glute-bridge', 'Dumbbell Glute Bridge', 'glutes', ARRAY['hamstrings']::text[], ARRAY['bench']::text[], 'hip_extension', 'strength', true, 'bilateral', false, 'beginner'),
  ('single-leg-glute-bridge', 'Single-Leg Glute Bridge', 'glutes', ARRAY['hamstrings']::text[], ARRAY['bench']::text[], 'hip_extension', 'strength', true, 'bilateral', false, 'beginner'),
  ('frog-pump', 'Frog Pump', 'glutes', ARRAY['hamstrings']::text[], ARRAY['bench']::text[], 'hip_extension', 'strength', true, 'bilateral', false, 'beginner'),
  ('cable-glute-kickback', 'Cable Glute Kickback', 'glutes', ARRAY['hamstrings']::text[], ARRAY['bench']::text[], 'hip_extension', 'strength', true, 'bilateral', false, 'beginner'),
  ('hip-abduction-machine', 'Hip Abduction Machine', 'abductors', ARRAY['glutes']::text[], ARRAY['machine']::text[], 'hip_abduction', 'strength', true, 'bilateral', false, 'beginner'),
  ('standing-cable-hip-abduction', 'Standing Cable Hip Abduction', 'abductors', ARRAY['glutes']::text[], ARRAY['machine']::text[], 'hip_abduction', 'strength', true, 'bilateral', false, 'beginner'),
  ('side-lying-hip-abduction', 'Side-Lying Hip Abduction', 'abductors', ARRAY['glutes']::text[], ARRAY['machine']::text[], 'hip_abduction', 'strength', true, 'bilateral', false, 'beginner'),
  ('banded-lateral-walk', 'Banded Lateral Walk', 'abductors', ARRAY['glutes']::text[], ARRAY['machine']::text[], 'hip_abduction', 'strength', true, 'bilateral', false, 'beginner'),
  ('banded-clamshell', 'Banded Clamshell', 'abductors', ARRAY['glutes']::text[], ARRAY['machine']::text[], 'hip_abduction', 'strength', true, 'bilateral', false, 'beginner'),
  ('hip-adduction-machine', 'Hip Adduction Machine', 'adductors', ARRAY['obliques']::text[], ARRAY['machine']::text[], 'hip_adduction', 'strength', true, 'bilateral', false, 'beginner'),
  ('standing-cable-hip-adduction', 'Standing Cable Hip Adduction', 'adductors', ARRAY['obliques']::text[], ARRAY['machine']::text[], 'hip_adduction', 'strength', true, 'bilateral', false, 'beginner'),
  ('copenhagen-plank', 'Copenhagen Plank', 'adductors', ARRAY['obliques']::text[], ARRAY['machine']::text[], 'hip_adduction', 'strength', true, 'bilateral', false, 'beginner'),
  ('standing-calf-raise', 'Standing Calf Raise', 'calves', ARRAY[]::text[], ARRAY['machine']::text[], 'calf_raise', 'strength', true, 'bilateral', false, 'beginner'),
  ('seated-calf-raise', 'Seated Calf Raise', 'calves', ARRAY[]::text[], ARRAY['machine']::text[], 'calf_raise', 'strength', true, 'bilateral', false, 'beginner'),
  ('leg-press-calf-raise', 'Leg Press Calf Raise', 'calves', ARRAY[]::text[], ARRAY['machine']::text[], 'calf_raise', 'strength', true, 'bilateral', false, 'beginner'),
  ('smith-machine-calf-raise', 'Smith Machine Calf Raise', 'calves', ARRAY[]::text[], ARRAY['machine']::text[], 'calf_raise', 'strength', true, 'bilateral', false, 'beginner'),
  ('donkey-calf-raise', 'Donkey Calf Raise', 'calves', ARRAY[]::text[], ARRAY['machine']::text[], 'calf_raise', 'strength', true, 'bilateral', false, 'beginner'),
  ('single-leg-calf-raise', 'Single-Leg Calf Raise', 'calves', ARRAY[]::text[], ARRAY['machine']::text[], 'calf_raise', 'strength', true, 'bilateral', false, 'beginner'),
  ('tibialis-raise', 'Tibialis Raise', 'calves', ARRAY[]::text[], ARRAY['machine']::text[], 'calf_raise', 'strength', true, 'bilateral', false, 'beginner'),
  ('cable-crunch', 'Cable Crunch', 'abs', ARRAY['obliques']::text[], ARRAY['cable']::text[], 'core_flexion', 'core', true, 'bilateral', false, 'beginner'),
  ('kneeling-cable-crunch', 'Kneeling Cable Crunch', 'abs', ARRAY['obliques']::text[], ARRAY['cable']::text[], 'core_flexion', 'core', true, 'bilateral', false, 'beginner'),
  ('standing-cable-crunch', 'Standing Cable Crunch', 'abs', ARRAY['obliques']::text[], ARRAY['cable']::text[], 'core_flexion', 'core', true, 'bilateral', false, 'beginner'),
  ('machine-crunch', 'Machine Crunch', 'abs', ARRAY['obliques']::text[], ARRAY['cable']::text[], 'core_flexion', 'core', true, 'bilateral', false, 'beginner'),
  ('decline-crunch', 'Decline Crunch', 'abs', ARRAY['obliques']::text[], ARRAY['cable']::text[], 'core_flexion', 'core', true, 'bilateral', false, 'beginner'),
  ('weighted-crunch', 'Weighted Crunch', 'abs', ARRAY['obliques']::text[], ARRAY['cable']::text[], 'core_flexion', 'core', true, 'bilateral', false, 'beginner'),
  ('reverse-crunch', 'Reverse Crunch', 'abs', ARRAY['obliques']::text[], ARRAY['cable']::text[], 'core_flexion', 'core', true, 'bilateral', false, 'beginner'),
  ('bicycle-crunch', 'Bicycle Crunch', 'abs', ARRAY['obliques']::text[], ARRAY['cable']::text[], 'core_flexion', 'core', true, 'bilateral', false, 'beginner'),
  ('v-up', 'V-Up', 'abs', ARRAY['obliques']::text[], ARRAY['cable']::text[], 'core_flexion', 'core', true, 'bilateral', false, 'beginner'),
  ('toe-touch', 'Toe Touch', 'abs', ARRAY['obliques']::text[], ARRAY['cable']::text[], 'core_flexion', 'core', true, 'bilateral', false, 'beginner'),
  ('dead-bug', 'Dead Bug', 'abs', ARRAY['obliques']::text[], ARRAY['cable']::text[], 'core_flexion', 'core', true, 'bilateral', false, 'beginner'),
  ('hanging-leg-raise', 'Hanging Leg Raise', 'abs', ARRAY['obliques']::text[], ARRAY['pull_up_bar','bodyweight']::text[], 'core_flexion', 'core', false, 'bilateral', true, 'beginner'),
  ('hanging-knee-raise', 'Hanging Knee Raise', 'abs', ARRAY['obliques']::text[], ARRAY['pull_up_bar','bodyweight']::text[], 'core_flexion', 'core', false, 'bilateral', true, 'beginner'),
  ('captain-s-chair-leg-raise', 'Captain''s Chair Leg Raise', 'abs', ARRAY['obliques']::text[], ARRAY['pull_up_bar','bodyweight']::text[], 'core_flexion', 'core', false, 'bilateral', true, 'beginner'),
  ('lying-leg-raise', 'Lying Leg Raise', 'abs', ARRAY['obliques']::text[], ARRAY['pull_up_bar','bodyweight']::text[], 'core_flexion', 'core', false, 'bilateral', true, 'beginner'),
  ('decline-leg-raise', 'Decline Leg Raise', 'abs', ARRAY['obliques']::text[], ARRAY['pull_up_bar','bodyweight']::text[], 'core_flexion', 'core', false, 'bilateral', true, 'beginner'),
  ('garhammer-raise', 'Garhammer Raise', 'abs', ARRAY['obliques']::text[], ARRAY['pull_up_bar','bodyweight']::text[], 'core_flexion', 'core', false, 'bilateral', true, 'beginner'),
  ('dragon-flag', 'Dragon Flag', 'abs', ARRAY['obliques']::text[], ARRAY['pull_up_bar','bodyweight']::text[], 'core_flexion', 'core', false, 'bilateral', true, 'beginner'),
  ('front-plank', 'Front Plank', 'abs', ARRAY['obliques']::text[], ARRAY['bodyweight']::text[], 'anti_extension', 'core', false, 'bilateral', true, 'beginner'),
  ('long-lever-plank', 'Long-Lever Plank', 'abs', ARRAY['obliques']::text[], ARRAY['bodyweight']::text[], 'anti_extension', 'core', false, 'bilateral', true, 'beginner'),
  ('rkc-plank', 'RKC Plank', 'abs', ARRAY['obliques']::text[], ARRAY['bodyweight']::text[], 'anti_extension', 'core', false, 'bilateral', true, 'beginner'),
  ('body-saw', 'Body Saw', 'abs', ARRAY['obliques']::text[], ARRAY['bodyweight']::text[], 'anti_extension', 'core', false, 'bilateral', true, 'beginner'),
  ('ab-wheel-rollout', 'Ab Wheel Rollout', 'abs', ARRAY['obliques']::text[], ARRAY['bodyweight']::text[], 'anti_extension', 'core', false, 'bilateral', true, 'beginner'),
  ('barbell-rollout', 'Barbell Rollout', 'abs', ARRAY['obliques']::text[], ARRAY['bodyweight']::text[], 'anti_extension', 'core', false, 'bilateral', true, 'beginner'),
  ('stability-ball-rollout', 'Stability-Ball Rollout', 'abs', ARRAY['obliques']::text[], ARRAY['bodyweight']::text[], 'anti_extension', 'core', false, 'bilateral', true, 'beginner'),
  ('hollow-body-hold', 'Hollow Body Hold', 'abs', ARRAY['obliques']::text[], ARRAY['bodyweight']::text[], 'anti_extension', 'core', false, 'bilateral', true, 'beginner'),
  ('side-plank', 'Side Plank', 'obliques', ARRAY['abs','adductors']::text[], ARRAY['bodyweight']::text[], 'anti_rotation', 'core', true, 'unilateral', true, 'beginner'),
  ('weighted-side-plank', 'Weighted Side Plank', 'obliques', ARRAY['abs','adductors']::text[], ARRAY['bodyweight']::text[], 'anti_rotation', 'core', true, 'unilateral', true, 'beginner'),
  ('copenhagen-side-plank', 'Copenhagen Side Plank', 'obliques', ARRAY['abs','adductors']::text[], ARRAY['bodyweight']::text[], 'anti_rotation', 'core', true, 'unilateral', true, 'beginner'),
  ('suitcase-plank', 'Suitcase Plank', 'obliques', ARRAY['abs','adductors']::text[], ARRAY['bodyweight']::text[], 'anti_rotation', 'core', true, 'unilateral', true, 'beginner'),
  ('pallof-press', 'Pallof Press', 'obliques', ARRAY['abs']::text[], ARRAY['cable']::text[], 'anti_rotation', 'core', true, 'bilateral', false, 'beginner'),
  ('half-kneeling-pallof-press', 'Half-Kneeling Pallof Press', 'obliques', ARRAY['abs']::text[], ARRAY['cable']::text[], 'anti_rotation', 'core', true, 'bilateral', false, 'beginner'),
  ('tall-kneeling-pallof-press', 'Tall-Kneeling Pallof Press', 'obliques', ARRAY['abs']::text[], ARRAY['cable']::text[], 'anti_rotation', 'core', true, 'bilateral', false, 'beginner'),
  ('pallof-press-hold', 'Pallof Press Hold', 'obliques', ARRAY['abs']::text[], ARRAY['cable']::text[], 'anti_rotation', 'core', true, 'bilateral', false, 'beginner'),
  ('cable-wood-chop', 'Cable Wood Chop', 'obliques', ARRAY['abs']::text[], ARRAY['cable']::text[], 'anti_rotation', 'core', true, 'bilateral', false, 'beginner'),
  ('cable-lift', 'Cable Lift', 'obliques', ARRAY['abs']::text[], ARRAY['cable']::text[], 'anti_rotation', 'core', true, 'bilateral', false, 'beginner'),
  ('landmine-rotation', 'Landmine Rotation', 'obliques', ARRAY['abs']::text[], ARRAY['cable']::text[], 'anti_rotation', 'core', true, 'bilateral', false, 'beginner'),
  ('russian-twist', 'Russian Twist', 'obliques', ARRAY['abs']::text[], ARRAY['cable']::text[], 'anti_rotation', 'core', true, 'bilateral', false, 'beginner'),
  ('medicine-ball-twist', 'Medicine-Ball Twist', 'obliques', ARRAY['abs']::text[], ARRAY['cable']::text[], 'anti_rotation', 'core', true, 'bilateral', false, 'beginner'),
  ('dumbbell-wrist-curl', 'Dumbbell Wrist Curl', 'forearms', ARRAY['traps']::text[], ARRAY['dumbbell']::text[], 'carry', 'strength', true, 'bilateral', false, 'beginner'),
  ('dumbbell-reverse-wrist-curl', 'Dumbbell Reverse Wrist Curl', 'forearms', ARRAY['traps']::text[], ARRAY['dumbbell']::text[], 'carry', 'strength', true, 'bilateral', false, 'beginner'),
  ('barbell-wrist-curl', 'Barbell Wrist Curl', 'forearms', ARRAY['traps']::text[], ARRAY['dumbbell']::text[], 'carry', 'strength', true, 'bilateral', false, 'beginner'),
  ('barbell-reverse-wrist-curl', 'Barbell Reverse Wrist Curl', 'forearms', ARRAY['traps']::text[], ARRAY['dumbbell']::text[], 'carry', 'strength', true, 'bilateral', false, 'beginner'),
  ('cable-wrist-curl', 'Cable Wrist Curl', 'forearms', ARRAY['traps']::text[], ARRAY['dumbbell']::text[], 'carry', 'strength', true, 'bilateral', false, 'beginner'),
  ('wrist-roller', 'Wrist Roller', 'forearms', ARRAY['traps']::text[], ARRAY['dumbbell']::text[], 'carry', 'strength', true, 'bilateral', false, 'beginner'),
  ('plate-pinch', 'Plate Pinch', 'forearms', ARRAY['traps']::text[], ARRAY['dumbbell']::text[], 'carry', 'strength', true, 'bilateral', false, 'beginner'),
  ('dead-hang', 'Dead Hang', 'forearms', ARRAY['traps']::text[], ARRAY['dumbbell']::text[], 'carry', 'strength', true, 'bilateral', false, 'beginner'),
  ('towel-dead-hang', 'Towel Dead Hang', 'forearms', ARRAY['traps']::text[], ARRAY['dumbbell']::text[], 'carry', 'strength', true, 'bilateral', false, 'beginner'),
  ('farmer-carry', 'Farmer Carry', 'forearms', ARRAY['traps']::text[], ARRAY['dumbbell']::text[], 'carry', 'strength', true, 'bilateral', false, 'beginner'),
  ('suitcase-carry', 'Suitcase Carry', 'forearms', ARRAY['traps']::text[], ARRAY['dumbbell']::text[], 'carry', 'strength', true, 'bilateral', false, 'beginner'),
  ('trap-bar-carry', 'Trap-Bar Carry', 'forearms', ARRAY['traps']::text[], ARRAY['dumbbell']::text[], 'carry', 'strength', true, 'bilateral', false, 'beginner'),
  ('rack-carry', 'Rack Carry', 'forearms', ARRAY['traps']::text[], ARRAY['dumbbell']::text[], 'carry', 'strength', true, 'bilateral', false, 'beginner'),
  ('bottoms-up-kettlebell-carry', 'Bottoms-Up Kettlebell Carry', 'forearms', ARRAY['traps']::text[], ARRAY['dumbbell']::text[], 'carry', 'strength', true, 'bilateral', false, 'beginner'),
  ('reverse-barbell-curl', 'Reverse Barbell Curl', 'forearms', ARRAY['biceps']::text[], ARRAY['ez_bar']::text[], 'elbow_flexion', 'strength', true, 'bilateral', false, 'beginner'),
  ('reverse-ez-bar-curl', 'Reverse EZ-Bar Curl', 'forearms', ARRAY['biceps']::text[], ARRAY['ez_bar']::text[], 'elbow_flexion', 'strength', true, 'bilateral', false, 'beginner'),
  ('dumbbell-reverse-curl', 'Dumbbell Reverse Curl', 'forearms', ARRAY['biceps']::text[], ARRAY['ez_bar']::text[], 'elbow_flexion', 'strength', true, 'bilateral', false, 'beginner'),
  ('hammer-curl', 'Hammer Curl', 'forearms', ARRAY['biceps']::text[], ARRAY['ez_bar']::text[], 'elbow_flexion', 'strength', true, 'bilateral', false, 'beginner'),
  ('rope-hammer-curl', 'Rope Hammer Curl', 'forearms', ARRAY['biceps']::text[], ARRAY['cable']::text[], 'elbow_flexion', 'strength', true, 'bilateral', false, 'beginner'),
  ('kettlebell-swing', 'Kettlebell Swing', 'glutes', ARRAY['hamstrings','lower_back']::text[], ARRAY['kettlebell']::text[], 'hinge', 'strength', false, 'bilateral', false, 'intermediate'),
  ('kettlebell-goblet-squat', 'Kettlebell Goblet Squat', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['kettlebell']::text[], 'squat', 'strength', false, 'bilateral', false, 'beginner'),
  ('single-arm-kettlebell-press', 'Single-Arm Kettlebell Press', 'front_delts', ARRAY['triceps','side_delts']::text[], ARRAY['kettlebell']::text[], 'vertical_push', 'strength', true, 'unilateral', false, 'intermediate'),
  ('single-arm-kettlebell-row', 'Single-Arm Kettlebell Row', 'upper_back', ARRAY['lats','biceps']::text[], ARRAY['kettlebell']::text[], 'horizontal_pull', 'strength', true, 'unilateral', false, 'beginner'),
  ('kettlebell-deadlift', 'Kettlebell Deadlift', 'glutes', ARRAY['hamstrings','lower_back']::text[], ARRAY['kettlebell']::text[], 'hinge', 'strength', false, 'bilateral', false, 'beginner'),
  ('turkish-get-up', 'Turkish Get-Up', 'abs', ARRAY['obliques','front_delts','glutes']::text[], ARRAY['kettlebell']::text[], 'anti_rotation', 'core', true, 'unilateral', false, 'intermediate'),
  ('resistance-band-chest-press', 'Resistance Band Chest Press', 'chest', ARRAY['triceps','front_delts']::text[], ARRAY['resistance_band']::text[], 'horizontal_push', 'strength', true, 'bilateral', false, 'beginner'),
  ('resistance-band-row', 'Resistance Band Row', 'upper_back', ARRAY['lats','biceps']::text[], ARRAY['resistance_band']::text[], 'horizontal_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('resistance-band-lat-pulldown', 'Resistance Band Lat Pulldown', 'lats', ARRAY['biceps','upper_back']::text[], ARRAY['resistance_band']::text[], 'vertical_pull', 'strength', true, 'bilateral', false, 'beginner'),
  ('resistance-band-biceps-curl', 'Resistance Band Biceps Curl', 'biceps', ARRAY['forearms']::text[], ARRAY['resistance_band']::text[], 'elbow_flexion', 'strength', true, 'bilateral', false, 'beginner'),
  ('resistance-band-triceps-pushdown', 'Resistance Band Triceps Pushdown', 'triceps', ARRAY[]::text[], ARRAY['resistance_band']::text[], 'elbow_extension', 'strength', true, 'bilateral', false, 'beginner'),
  ('resistance-band-lateral-raise', 'Resistance Band Lateral Raise', 'side_delts', ARRAY['traps']::text[], ARRAY['resistance_band']::text[], 'shoulder_abduction', 'strength', true, 'bilateral', false, 'beginner'),
  ('resistance-band-face-pull', 'Resistance Band Face Pull', 'rear_delts', ARRAY['upper_back','traps']::text[], ARRAY['resistance_band']::text[], 'horizontal_pull', 'strength', false, 'bilateral', false, 'beginner'),
  ('resistance-band-squat', 'Resistance Band Squat', 'quads', ARRAY['glutes','adductors']::text[], ARRAY['resistance_band']::text[], 'squat', 'strength', false, 'bilateral', false, 'beginner'),
  ('resistance-band-hip-abduction', 'Resistance Band Hip Abduction', 'abductors', ARRAY['glutes']::text[], ARRAY['resistance_band']::text[], 'hip_abduction', 'strength', true, 'bilateral', false, 'beginner'),
  ('kettlebell-farmer-carry', 'Kettlebell Farmer Carry', 'forearms', ARRAY['traps']::text[], ARRAY['kettlebell']::text[], 'carry', 'carry', true, 'bilateral', false, 'beginner');

INSERT INTO public.bulk_exercises (
  id, owner_id, slug, name, primary_muscle, secondary_muscles, equipment,
  movement_pattern, category, supports_unilateral, default_unilateral_mode,
  is_bodyweight, is_system, active, min_experience
)
SELECT
  'system:' || slug, NULL, slug, name, primary_muscle, secondary_muscles, equipment,
  movement_pattern, category, supports_unilateral, default_unilateral_mode,
  is_bodyweight, true, true, min_experience
FROM bulk_exercise_seed
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  name = EXCLUDED.name,
  primary_muscle = EXCLUDED.primary_muscle,
  secondary_muscles = EXCLUDED.secondary_muscles,
  equipment = EXCLUDED.equipment,
  movement_pattern = EXCLUDED.movement_pattern,
  category = EXCLUDED.category,
  supports_unilateral = EXCLUDED.supports_unilateral,
  default_unilateral_mode = EXCLUDED.default_unilateral_mode,
  is_bodyweight = EXCLUDED.is_bodyweight,
  active = true,
  min_experience = EXCLUDED.min_experience;

-- Correct equipment for mixed variation families while keeping one canonical row per movement.
UPDATE public.bulk_exercises AS exercise
SET equipment = correction.equipment
FROM (VALUES
  ('system:machine-lat-pulldown', ARRAY['machine']::text[]),
  ('system:dumbbell-pullover', ARRAY['dumbbell','bench']::text[]),
  ('system:machine-pullover', ARRAY['machine']::text[]),
  ('system:dumbbell-shrug', ARRAY['dumbbell']::text[]),
  ('system:smith-machine-shrug', ARRAY['smith_machine']::text[]),
  ('system:cable-shrug', ARRAY['cable']::text[]),
  ('system:machine-shrug', ARRAY['machine']::text[]),
  ('system:smith-machine-shoulder-press', ARRAY['smith_machine','bench']::text[]),
  ('system:cable-lateral-raise', ARRAY['cable']::text[]),
  ('system:behind-the-back-cable-lateral-raise', ARRAY['cable']::text[]),
  ('system:leaning-cable-lateral-raise', ARRAY['cable']::text[]),
  ('system:machine-lateral-raise', ARRAY['machine']::text[]),
  ('system:single-arm-machine-lateral-raise', ARRAY['machine']::text[]),
  ('system:plate-lateral-raise', ARRAY['plate']::text[]),
  ('system:cable-front-raise', ARRAY['cable']::text[]),
  ('system:plate-front-raise', ARRAY['plate']::text[]),
  ('system:barbell-front-raise', ARRAY['barbell']::text[]),
  ('system:reverse-pec-deck', ARRAY['machine']::text[]),
  ('system:bent-over-dumbbell-rear-delt-raise', ARRAY['dumbbell']::text[]),
  ('system:chest-supported-rear-delt-raise', ARRAY['dumbbell','bench']::text[]),
  ('system:band-pull-apart', ARRAY['resistance_band']::text[]),
  ('system:barbell-skull-crusher', ARRAY['barbell','bench']::text[]),
  ('system:jm-press', ARRAY['barbell','bench']::text[]),
  ('system:close-grip-bench-press', ARRAY['barbell','bench']::text[]),
  ('system:smith-machine-split-squat', ARRAY['smith_machine']::text[]),
  ('system:nordic-hamstring-curl', ARRAY['bodyweight']::text[]),
  ('system:assisted-nordic-curl', ARRAY['bodyweight','resistance_band']::text[]),
  ('system:sliding-leg-curl', ARRAY['bodyweight']::text[]),
  ('system:stability-ball-leg-curl', ARRAY['bodyweight']::text[]),
  ('system:dumbbell-romanian-deadlift', ARRAY['dumbbell']::text[]),
  ('system:cable-pull-through', ARRAY['cable']::text[]),
  ('system:trap-bar-deadlift', ARRAY['trap_bar']::text[]),
  ('system:smith-machine-hip-thrust', ARRAY['smith_machine','bench']::text[]),
  ('system:machine-hip-thrust', ARRAY['machine']::text[]),
  ('system:dumbbell-hip-thrust', ARRAY['dumbbell','bench']::text[]),
  ('system:cable-glute-kickback', ARRAY['cable']::text[]),
  ('system:standing-cable-hip-abduction', ARRAY['cable']::text[]),
  ('system:banded-lateral-walk', ARRAY['resistance_band']::text[]),
  ('system:banded-clamshell', ARRAY['resistance_band']::text[]),
  ('system:standing-cable-hip-adduction', ARRAY['cable']::text[]),
  ('system:copenhagen-plank', ARRAY['bodyweight']::text[]),
  ('system:smith-machine-calf-raise', ARRAY['smith_machine']::text[]),
  ('system:single-leg-calf-raise', ARRAY['bodyweight']::text[]),
  ('system:machine-crunch', ARRAY['machine']::text[]),
  ('system:decline-crunch', ARRAY['bodyweight','bench']::text[]),
  ('system:weighted-crunch', ARRAY['plate']::text[]),
  ('system:reverse-crunch', ARRAY['bodyweight']::text[]),
  ('system:bicycle-crunch', ARRAY['bodyweight']::text[]),
  ('system:v-up', ARRAY['bodyweight']::text[]),
  ('system:toe-touch', ARRAY['bodyweight']::text[]),
  ('system:dead-bug', ARRAY['bodyweight']::text[]),
  ('system:landmine-rotation', ARRAY['barbell']::text[]),
  ('system:russian-twist', ARRAY['bodyweight']::text[]),
  ('system:medicine-ball-twist', ARRAY['bodyweight']::text[]),
  ('system:barbell-wrist-curl', ARRAY['barbell']::text[]),
  ('system:barbell-reverse-wrist-curl', ARRAY['barbell']::text[]),
  ('system:cable-wrist-curl', ARRAY['cable']::text[]),
  ('system:plate-pinch', ARRAY['plate']::text[]),
  ('system:dead-hang', ARRAY['pull_up_bar','bodyweight']::text[]),
  ('system:towel-dead-hang', ARRAY['pull_up_bar','bodyweight']::text[]),
  ('system:trap-bar-carry', ARRAY['trap_bar']::text[]),
  ('system:rack-carry', ARRAY['barbell']::text[]),
  ('system:bottoms-up-kettlebell-carry', ARRAY['kettlebell']::text[]),
  ('system:reverse-barbell-curl', ARRAY['barbell']::text[]),
  ('system:dumbbell-reverse-curl', ARRAY['dumbbell']::text[]),
  ('system:hammer-curl', ARRAY['dumbbell']::text[])
) AS correction(id, equipment)
WHERE exercise.id = correction.id;

UPDATE public.bulk_exercises
SET movement_pattern = 'rotation'
WHERE id IN ('system:landmine-rotation','system:russian-twist','system:medicine-ball-twist');

DROP TABLE bulk_exercise_seed;
