// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";
import { missingPublicSupabaseVariables, resolvePublicSupabaseConfiguration } from "./environment";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient() {
  // Keep these as direct Vite property reads. Vite statically replaces direct
  // accesses, while passing the whole import.meta.env object can omit managed
  // variables from the production browser bundle.
  const buildSupabaseUrl = import.meta.env.VITE_SUPABASE_URL;
  const buildSupabasePublishableKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
  const runtimeEnvironment = typeof process !== "undefined" ? process.env : {};
  const configuration = resolvePublicSupabaseConfiguration(
    {
      VITE_SUPABASE_URL: buildSupabaseUrl,
      VITE_SUPABASE_PUBLISHABLE_KEY: buildSupabasePublishableKey,
    },
    runtimeEnvironment,
  );
  const SUPABASE_URL = configuration.url;
  const SUPABASE_PUBLISHABLE_KEY = configuration.publishableKey;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = missingPublicSupabaseVariables(configuration);
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
